{{ if .Values.enabled.electronics  }}
apiVersion: v1
kind: Service
metadata:
  name: electronics-svc
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }} 
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9001
  - name: https
    port: 9002
  selector:
    app: {{ template "fullname" . }}
---
apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  name: electronics-api
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }} 
spec:
    authentication: []
    hostname: electronics
    service:
      name: electronics-svc
      port: 9001
---
{{ end }}
{{ if .Values.enabled.apparel }}
apiVersion: v1
kind: Service
metadata:
  name: apparel-svc
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }} 
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9001
  - name: https
    port: 9002
  selector:
    app: {{ template "fullname" . }}
---
apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  name: apparel-api
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }} 
spec:
    authentication: []
    hostname: apparel-uk
    service:
      name: apparel-svc
      port: 9001
---
{{ end }}
{{ if .Values.enabled.powertools }}
apiVersion: v1
kind: Service
metadata:
  name: powertools-svc
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }} 
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9001
  - name: https
    port: 9002
  selector:
    app: {{ template "fullname" . }}
---
apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  name: powertools-api
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }} 
spec:
    authentication: []
    hostname: powertools
    service:
      name: powertools-svc
      port: 9001
---
{{ end }}
apiVersion: v1
kind: Service
metadata:
  name: backoffice-svc
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }} 
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9001
  - name: https
    port: 9002
  selector:
    app: {{ template "fullname" . }}
---
apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  name: backoffice
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }} 
spec:
    authentication: []
    hostname: backoffice
    service:
      name: backoffice-svc
      port: 9001
---
