name: annexcloud-connector
version: 0.1.0
description: "Enables the preview integration of Annex Cloud. It is not recommended for production scenarios."
id: faebbe18-0a84-11e5-ab14-d663bd873e54
displayName: "[Preview] Annex Cloud - Connector"
tags: preview,annexcloud,connector
labels: 
  preview: "true"
providerDisplayName: SAP
longDescription: "Integrates Annex Cloud in preview mode by registering its REST APIs in an existing Application and enables consuming the APIs from a lambda or microservice. It is not recommended for production use."
documentationURL: https://www.annexcloud.com
bindable: false
provisionOnlyOnce: true
imageUrl: 
