apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "bundle.fullname" . }}
    component: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}
data:
  SYSTEM_URL	: {{ .Values.system_url }}/{{ .Values.site_id }}
  APPLICATION_NAME: {{ .Values.application_name | quote }}
  PROVIDER_NAME: SAP
  PRODUCT_NAME: Annex Cloud
  APP_KIND: rest-with-apikey
  API_DESCRIPTION: "APIs for Annex Cloud"
  API_SPECIFICATION_URL: https://raw.githubusercontent.com/brendandobbs/annexcloud-connector/master/api-docs/annexcloud.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}-api
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "bundle.fullname" . }}
    component: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}
data:
  params.json: |-
    {
      "access_token": {{ .Values.access_token | quote }}
    }
  apis.json: |-
    []
